# Generated by Django 4.0.3 on 2022-03-27 00:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=1)),
                ('details', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('other1', models.CharField(default='Doe', max_length=50)),
                ('other2', models.CharField(default='Jane', max_length=50)),
                ('other3', models.CharField(default='phil', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField(default=1)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('other1', models.CharField(default='Doe', max_length=50)),
                ('other2', models.CharField(default='Jane', max_length=50)),
                ('other3', models.CharField(default='phil', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff', models.CharField(max_length=50)),
                ('number_plate', models.CharField(max_length=10)),
                ('fuel', models.CharField(max_length=50)),
                ('litres', models.FloatField(default=1)),
                ('f', models.IntegerField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('year', models.IntegerField(default=2022)),
                ('month', models.IntegerField(default=3)),
                ('day', models.IntegerField(default=27)),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(max_length=2000)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=2000)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=12)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('idno', models.IntegerField()),
                ('age', models.CharField(default=18, max_length=2)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('profile', models.ImageField(default='default.jpg', upload_to='images')),
                ('address', models.CharField(default='John', max_length=50)),
                ('other1', models.CharField(default='Doe', max_length=50)),
                ('other2', models.CharField(default='Jane', max_length=50)),
                ('other3', models.CharField(default='phil', max_length=50)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=2000)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('customer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
