# Generated by Django 4.0.3 on 2022-03-16 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=12)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('idno', models.IntegerField()),
                ('age', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ImageField(default='default.jpg', upload_to='images')),
                ('address', models.CharField(default='John', max_length=50)),
                ('other1', models.CharField(default='Doe', max_length=50)),
                ('other2', models.CharField(default='Jane', max_length=50)),
                ('other3', models.CharField(default='phil', max_length=50)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
