# Generated by Django 4.0.3 on 2022-03-16 21:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='age',
            field=models.IntegerField(default=18),
        ),
    ]
