# Generated by Django 4.0.3 on 2022-03-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_staff_date_alter_staff_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField(default=1)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('other1', models.CharField(default='Doe', max_length=50)),
                ('other2', models.CharField(default='Jane', max_length=50)),
                ('other3', models.CharField(default='phil', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff', models.CharField(max_length=50)),
                ('number_plate', models.CharField(max_length=10)),
                ('fuel', models.CharField(max_length=50)),
                ('litres', models.FloatField(default=1)),
                ('f', models.IntegerField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('other1', models.CharField(default='Doe', max_length=50)),
                ('other2', models.CharField(default='Jane', max_length=50)),
                ('other3', models.CharField(default='phil', max_length=50)),
            ],
        ),
    ]
