# Generated by Django 4.0.3 on 2022-03-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_category_date_alter_contact_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell',
            name='other1',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='other2',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='other3',
        ),
        migrations.AddField(
            model_name='sell',
            name='day',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='sell',
            name='month',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='sell',
            name='year',
            field=models.IntegerField(default=2022),
        ),
    ]
