# Generated by Django 4.0.3 on 2022-03-25 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('other1', models.CharField(default='Doe', max_length=50)),
                ('other2', models.CharField(default='Jane', max_length=50)),
                ('other3', models.CharField(default='phil', max_length=50)),
            ],
        ),
    ]
