# Generated by Django 4.0.3 on 2022-03-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='num',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sell',
            name='day',
            field=models.IntegerField(default=26),
        ),
    ]
